version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: monthly
      pull-request-branch-name:
          separator: "-"
      ignore:
          - dependency-name: "*"
            update-types:
                - "version-update:semver-major"
    - package-ecosystem: npm
      directory: /frontend
      schedule:
          interval: monthly
      pull-request-branch-name:
          separator: "-"
      ignore:
          - dependency-name: "*"
            update-types:
                - "version-update:semver-major"
    - package-ecosystem: npm
      directory: /backend
      schedule:
          interval: monthly
      pull-request-branch-name:
          separator: "-"
      ignore:
          - dependency-name: "*"
            update-types:
                - "version-update:semver-major"
